baseURL: /
title: Flora of the Great Lakes
theme: hugo-book
disablePathToLower: yes
enableGitInfo: yes
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
markup:
  goldmark:
    renderer:
      unsafe: yes
  tableOfContents:
    startLevel: 1
languages:
  en:
    contentDir: content
    languageName: English
    weight: 1
menu:
  after:
    - name: Flora of the Great Lakes
      url: http://floragreatlakes.info/html/flora.html
      weight: 10
    - name: Mid Coast Native Plants (PDF)
      url: https://www.midcoast.nsw.gov.au/files/assets/public/document-resources/environment-docs/trees-amp-plants/indigenous-plants-of-greater-taree-version-3.pdf
      weight: 20
params:
  BookComments: yes
  BookDateFormat: January 2, 2006
  BookEditPath: edit/main/exampleSite
  BookPortableLinks: yes
  BookRepo: https://github.com/alex-shpak/hugo-book
  BookSearch: yes
  BookSection: docs
  BookServiceWorker: yes
  BookTheme: light
  BookToC: yes
  BookTranslatedOnly: no
